[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kissing_solver"
version = "0.1.0"

[tool.pytest.ini_options]
testpaths = ["src"]
python_files = ["*.py"]